/**
 * BarakaFlow - Main Application Component
 * 
 * This is the root component that manages:
 * - User authentication state
 * - Task data fetching and management
 * - Routing between login/signup and main app
 * - Overall application state
 * 
 * @component
 */

import { useState, useEffect } from 'react';
import { Task } from './types';
import { TodayOverview } from './components/TodayOverview/TodayOverview';
import { TaskTable } from './components/TaskTable/TaskTable';
import { Login } from './components/Login/Login';
import { Signup } from './components/Signup/Signup';
import { authApi, tasksApi } from './api/api';
import styles from './App.module.css';

function App() {
  // Application state management
  const [tasks, setTasks] = useState<Task[]>([]); // All user tasks
  const [loading, setLoading] = useState(true); // Loading state for tasks
  const [isAuthenticated, setIsAuthenticated] = useState(false); // User authentication status
  const [isCheckingAuth, setIsCheckingAuth] = useState(true); // Initial auth check status
  const [showSignup, setShowSignup] = useState(false); // Toggle between login/signup screens
  const [currentUser, setCurrentUser] = useState<{ name: string; email?: string } | null>(null); // Current authenticated user

  /**
   * Check authentication status on component mount
   * Verifies if user has a valid JWT token stored in localStorage
   */
  useEffect(() => {
    checkAuth();
  }, []);

  /**
   * Load tasks when user becomes authenticated
   * Only fetches tasks after successful authentication
   */
  useEffect(() => {
    if (isAuthenticated) {
      loadTasks();
      // Ensure currentUser is set if authenticated but not yet set
      if (!currentUser) {
        const user = authApi.getCurrentUser();
        if (user) {
          setCurrentUser(user);
        }
      }
    }
  }, [isAuthenticated, currentUser]);

  /**
   * Verify user authentication token
   * Checks localStorage for token and validates it with backend
   */
  const checkAuth = async () => {
    try {
      // First, try to get user from localStorage (fast, works even if backend is slow)
      const storedUser = authApi.getCurrentUser();
      if (storedUser) {
        // Set user immediately from localStorage for instant UI update
        setCurrentUser({ name: storedUser.name, email: storedUser.email });
        setIsAuthenticated(true);
      }

      // Then verify token with backend (if token exists)
      if (authApi.isAuthenticated()) {
        try {
          const response = await authApi.verify();
          // Update with fresh data from backend
          setIsAuthenticated(true);
          setCurrentUser({ name: response.user.name, email: response.user.email });
        } catch (verifyError) {
          // If verify fails but we have localStorage user, keep them logged in
          // This handles cases where backend is temporarily unavailable
          if (!storedUser) {
            // No localStorage user and verify failed - logout
            authApi.logout();
            setIsAuthenticated(false);
            setCurrentUser(null);
          }
          // If we have storedUser, keep them logged in (already set above)
        }
      } else if (!storedUser) {
        // No token and no stored user - not authenticated
        setIsAuthenticated(false);
        setCurrentUser(null);
      }
    } catch (error) {
      // Fallback: try localStorage one more time
      const storedUser = authApi.getCurrentUser();
      if (storedUser) {
        setCurrentUser({ name: storedUser.name, email: storedUser.email });
        setIsAuthenticated(true);
      } else {
        authApi.logout();
        setIsAuthenticated(false);
        setCurrentUser(null);
      }
    } finally {
      setIsCheckingAuth(false);
    }
  };

  /**
   * Fetch all tasks for the authenticated user
   * Handles authentication errors by logging out user
   */
  const loadTasks = async () => {
    try {
      setLoading(true);
      const loadedTasks = await tasksApi.getTasks();
      setTasks(loadedTasks);
    } catch (error) {
      console.error('Failed to load tasks:', error);
      // If auth error (invalid/expired token), automatically logout
      if (error instanceof Error && error.message.includes('token')) {
        authApi.logout();
        setIsAuthenticated(false);
      }
    } finally {
      setLoading(false);
    }
  };

  /**
   * Create a new task
   * @param taskData - Task data without id and createdAt (generated by backend)
   */
  const handleCreateTask = async (taskData: Omit<Task, 'id' | 'createdAt'>) => {
    try {
      await tasksApi.createTask(taskData);
      // Reload tasks to get proper sorting
      await loadTasks();
    } catch (error) {
      console.error('Failed to create task:', error);
    }
  };

  /**
   * Update an existing task
   * @param id - Task ID to update
   * @param updates - Partial task data with fields to update
   */
  const handleUpdateTask = async (id: string, updates: Partial<Task>) => {
    try {
      await tasksApi.updateTask(id, updates);
      // Reload tasks to ensure UI reflects latest data from backend
      await loadTasks();
    } catch (error) {
      console.error('Failed to update task:', error);
    }
  };

  /**
   * Delete a task
   * @param id - Task ID to delete
   */
  const handleDeleteTask = async (id: string) => {
    try {
      await tasksApi.deleteTask(id);
      // Optimistically update UI by removing task from local state
      setTasks(tasks.filter((t) => t.id !== id));
    } catch (error) {
      console.error('Failed to delete task:', error);
    }
  };

  /**
   * Handle successful login/signup
   * Sets authentication state and hides signup screen
   */
  const handleLoginSuccess = () => {
    setIsAuthenticated(true);
    setShowSignup(false);
    // Get current user from localStorage (set by authApi)
    const user = authApi.getCurrentUser();
    if (user) {
      setCurrentUser({ name: user.name, email: user.email });
    }
  };

  /**
   * Handle user logout
   * Clears authentication token and resets application state
   */
  const handleLogout = () => {
    authApi.logout();
    setIsAuthenticated(false);
    setTasks([]);
    setCurrentUser(null);
  };

  // Show loading while checking auth
  if (isCheckingAuth) {
    return (
      <div className={styles.app}>
        <div className={styles.loading}>Loading...</div>
      </div>
    );
  }

  // Show auth screens if not authenticated
  if (!isAuthenticated) {
    return showSignup ? (
      <Signup
        onSignupSuccess={handleLoginSuccess}
        onSwitchToLogin={() => setShowSignup(false)}
      />
    ) : (
      <Login
        onLoginSuccess={handleLoginSuccess}
        onSwitchToSignup={() => setShowSignup(true)}
      />
    );
  }

  // Show main app if authenticated
  // Get user name directly from localStorage - simple and always works
  const getUserName = (): string | null => {
    try {
      const userStr = localStorage.getItem('current_user');
      if (userStr) {
        const user = JSON.parse(userStr);
        console.log('User data from localStorage:', user); // Debug log
        return user.name || null;
      }
    } catch (e) {
      console.error('Error reading user from localStorage:', e); // Debug log
    }
    return null;
  };

  const userName = getUserName();
  console.log('Welcome message userName:', userName); // Debug log

  return (
    <div className={styles.app}>
      <div className={styles.container}>
        <header className={styles.header}>
          <div className={styles.headerTop}>
            <div className={styles.headerTitle}>
              <h1 className={styles.title}>BarakaFlow</h1>
              {userName && (
                <span className={styles.welcomeText}>
                  Welcome, {userName}! 👋
                </span>
              )}
            </div>
            <div className={styles.headerActions}>
              <TodayOverview tasks={tasks} />
              <button onClick={handleLogout} className={styles.logoutButton}>
                Logout
              </button>
            </div>
          </div>
        </header>

        {loading ? (
          <div className={styles.loading}>Loading your tasks...</div>
        ) : (
          <TaskTable
            tasks={tasks}
            onUpdate={handleUpdateTask}
            onDelete={handleDeleteTask}
            onCreateTask={handleCreateTask}
          />
        )}
      </div>
    </div>
  );
}

export default App;
